version: '2.1'
services:
  verdaccio:
    image: verdaccio/verdaccio:5
    container_name: consent-manager-examples-local-package-registry
    ports:
      - '4873:4873'
    volumes:
      - './.verdaccio/storage:/verdaccio/storage'
      - './.verdaccio/conf:/verdaccio/conf'
volumes:
  verdaccio:
    driver: local
